nim     = input("masukan nim anda:")
nama    = input("masukan nama lengkap:")
kelas   = input( "masukan kelas anda:")
usia    = input( "masukan usia:")
print("==================================")
print("identitas mahasiswa")
print("==================================")
print("nim mahasiswa:",nim)
print("nama lengkap:",nama)
print("kelas saat ini:",kelas)
print("usia anda:",usia)
print("======================")
